// Website (shreeji-gold) के पहले से बने designs — उसकी src/data/catalog.js से एक बार निकाले गए.
// "npm run seed:catalog" या admin के "पुराने designs वापस लाएं" बटन से ये catalog में जुड़ते हैं.
// फोटो अभी Unsplash की stock फोटो हैं — admin में Edit करके दुकान की अपनी फोटो लगा सकते हैं.
export const WEBSITE_CATALOG = [
  {
    "id": "SG0001",
    "name": "Bloom Bud Gold Ring",
    "type": "Rings",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Daily Wear",
    "image": "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 1
  },
  {
    "id": "SG0002",
    "name": "Tropical Canopy Gold Drop Earrings",
    "type": "Earrings",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Festive",
    "image": "https://images.unsplash.com/photo-1653227907864-560dce4c252d?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 2
  },
  {
    "id": "SG0003",
    "name": "Canopy Frame Drop Earrings",
    "type": "Earrings",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Festive",
    "image": "https://images.unsplash.com/photo-1701777892740-88419a701472?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 3
  },
  {
    "id": "SG0004",
    "name": "Alluring Gold Beaded Finger Ring",
    "type": "Rings",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Festive",
    "image": "https://images.unsplash.com/photo-1626784215021-2e39ccf971cd?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 4
  },
  {
    "id": "SG0005",
    "name": "Breathtaking 22K Yellow Gold Floral Ring",
    "type": "Rings",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Festive",
    "image": "https://images.unsplash.com/photo-1608508644127-ba99d7732fee?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 5
  },
  {
    "id": "SG0006",
    "name": "Fancy Traditional Gold and Diamond Ring",
    "type": "Rings",
    "metal": "Diamond",
    "wearer": "Men",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1615655114865-4cc1bda5901e?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 6
  },
  {
    "id": "SG0007",
    "name": "Brilliant 22K Gold and Ruby Flower Ring",
    "type": "Rings",
    "metal": "Gemstone",
    "wearer": "Women",
    "occasion": "Festive",
    "image": "https://images.unsplash.com/photo-1723802205505-2f88b2227718?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 7
  },
  {
    "id": "SG0008",
    "name": "Grand Cluster Diamond Nose Ring",
    "type": "Nose Pins",
    "metal": "Diamond",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1578503803703-e818b8a0e00b?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 8
  },
  {
    "id": "SG0009",
    "name": "Elegant Gold and Diamond Nose Pin",
    "type": "Nose Pins",
    "metal": "Diamond",
    "wearer": "Women",
    "occasion": "Daily Wear",
    "image": "https://images.unsplash.com/photo-1588891805983-fee12d508e31?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 9
  },
  {
    "id": "SG0010",
    "name": "Leaf Inspired Gold and Diamond Nose Pin",
    "type": "Nose Pins",
    "metal": "Diamond",
    "wearer": "Women",
    "occasion": "Daily Wear",
    "image": "https://images.unsplash.com/photo-1727990865600-91f8cb8b0168?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 10
  },
  {
    "id": "SG0011",
    "name": "Flawless Diamond Nose Ring",
    "type": "Nose Pins",
    "metal": "Diamond",
    "wearer": "Women",
    "occasion": "Daily Wear",
    "image": "https://images.unsplash.com/photo-1601121141499-17ae80afc03a?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 11
  },
  {
    "id": "SG0012",
    "name": "Slender Gold Nath for the Indian Bride",
    "type": "Nose Pins",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1603974372039-adc49044b6bd?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 12
  },
  {
    "id": "SG0013",
    "name": "Solitary Flower Mangalsutra",
    "type": "Mangalsutra",
    "metal": "Diamond",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1569397288884-4d43d6738fbd?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 13
  },
  {
    "id": "SG0014",
    "name": "Kundan Layered Bridal Necklace",
    "type": "Necklaces",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1722410180687-b05b50922362?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 14
  },
  {
    "id": "SG0015",
    "name": "Amethyst Bloom Beaded Necklace",
    "type": "Necklaces",
    "metal": "Gemstone",
    "wearer": "Women",
    "occasion": "Festive",
    "image": "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 15
  },
  {
    "id": "SG0016",
    "name": "Everyday Gold Rope Chain",
    "type": "Chains",
    "metal": "18K Gold",
    "wearer": "Men",
    "occasion": "Daily Wear",
    "image": "https://images.unsplash.com/photo-1611107683227-e9060eccd846?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 16
  },
  {
    "id": "SG0017",
    "name": "Heartbeat Charm Pendant",
    "type": "Pendants",
    "metal": "18K Gold",
    "wearer": "Women",
    "occasion": "Gifting",
    "image": "https://images.unsplash.com/photo-1623321673989-830eff0fd59f?auto=format&fit=crop&w=700&q=80",
    "isNew": true,
    "bestseller": false,
    "order": 17
  },
  {
    "id": "SG0018",
    "name": "Temple Bloom Long Haram",
    "type": "Necklaces",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1705326452390-3ecf6070595f?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 18
  },
  {
    "id": "SG0019",
    "name": "Regal Pearl and Gold Choker",
    "type": "Necklaces",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Festive",
    "image": "https://images.unsplash.com/photo-1721103418312-b0057a8c31c2?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 19
  },
  {
    "id": "SG0020",
    "name": "Ruby Drop Beaded Necklace",
    "type": "Necklaces",
    "metal": "Gemstone",
    "wearer": "Women",
    "occasion": "Festive",
    "image": "https://images.unsplash.com/photo-1600862754152-80a263dd564f?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 20
  },
  {
    "id": "SG0021",
    "name": "Layered Gold and Silver Necklace",
    "type": "Necklaces",
    "metal": "18K Gold",
    "wearer": "Women",
    "occasion": "Office Wear",
    "image": "https://images.unsplash.com/photo-1601121141461-920cb1993441?auto=format&fit=crop&w=700&q=80",
    "isNew": true,
    "bestseller": false,
    "order": 21
  },
  {
    "id": "SG0022",
    "name": "Crowned Blossom Necklace",
    "type": "Necklaces",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1685970731194-e27b477e87ba?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 22
  },
  {
    "id": "SG0023",
    "name": "Ivory Grace Bridal Set",
    "type": "Bridal Sets",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1705326454924-f6777522b030?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 23
  },
  {
    "id": "SG0024",
    "name": "Emerald Court Bridal Set",
    "type": "Bridal Sets",
    "metal": "Gemstone",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1722410180670-b6d5a2e704fa?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 24
  },
  {
    "id": "SG0025",
    "name": "Midnight Gold Statement Set",
    "type": "Bridal Sets",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Festive",
    "image": "https://images.unsplash.com/photo-1651160670627-2896ddf7822f?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 25
  },
  {
    "id": "SG0026",
    "name": "Tortoise Charm Gold Pendant",
    "type": "Pendants",
    "metal": "18K Gold",
    "wearer": "Kids",
    "occasion": "Gifting",
    "image": "https://images.unsplash.com/photo-1722410180644-ff76ef805092?auto=format&fit=crop&w=700&q=80",
    "isNew": true,
    "bestseller": false,
    "order": 26
  },
  {
    "id": "SG0027",
    "name": "Beaded Kada Pair",
    "type": "Bangles",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1626784215013-13322cb0e471?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 27
  },
  {
    "id": "SG0028",
    "name": "Single Twist Gold Bangle",
    "type": "Bangles",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Daily Wear",
    "image": "https://images.unsplash.com/photo-1626784214765-754de4c5a77b?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 28
  },
  {
    "id": "SG0029",
    "name": "Amethyst Line Long Chain",
    "type": "Chains",
    "metal": "Gemstone",
    "wearer": "Women",
    "occasion": "Office Wear",
    "image": "https://images.unsplash.com/photo-1589095053205-8fc842336f4a?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 29
  },
  {
    "id": "SG0030",
    "name": "Petal Stud Earrings",
    "type": "Earrings",
    "metal": "18K Gold",
    "wearer": "Women",
    "occasion": "Daily Wear",
    "image": "https://images.unsplash.com/photo-1671644730555-916aa8d8157f?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 30
  },
  {
    "id": "SG0031",
    "name": "Purple Vine Drop Earrings",
    "type": "Earrings",
    "metal": "Gemstone",
    "wearer": "Women",
    "occasion": "Festive",
    "image": "https://images.unsplash.com/photo-1601121141418-c1caa10a2a0b?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 31
  },
  {
    "id": "SG0032",
    "name": "Antique Temple Jhumkas",
    "type": "Earrings",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1695049918857-1e27d67782e5?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 32
  },
  {
    "id": "SG0033",
    "name": "Classic Vati Mangalsutra",
    "type": "Mangalsutra",
    "metal": "18K Gold",
    "wearer": "Women",
    "occasion": "Daily Wear",
    "image": "https://images.unsplash.com/photo-1620656798579-1984d9e87df7?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 33
  },
  {
    "id": "SG0034",
    "name": "Rose Gold Everyday Band",
    "type": "Rings",
    "metal": "Rose Gold",
    "wearer": "Women",
    "occasion": "Daily Wear",
    "image": "https://images.unsplash.com/photo-1615655114865-4cc1bda5901e?auto=format&fit=crop&w=700&q=80",
    "isNew": true,
    "bestseller": false,
    "order": 34
  },
  {
    "id": "SG0035",
    "name": "Solitaire Halo Engagement Ring",
    "type": "Rings",
    "metal": "Diamond",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1608508644127-ba99d7732fee?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 35
  },
  {
    "id": "SG0036",
    "name": "Heirloom Kada in 22K Gold",
    "type": "Bangles",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1654781456542-fdd1683c79c3?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 36
  },
  {
    "id": "SG0037",
    "name": "Office Line Diamond Studs",
    "type": "Earrings",
    "metal": "Diamond",
    "wearer": "Women",
    "occasion": "Office Wear",
    "image": "https://images.unsplash.com/photo-1727990865600-91f8cb8b0168?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 37
  },
  {
    "id": "SG0038",
    "name": "Gifting Gold Coin Pendant",
    "type": "Pendants",
    "metal": "22K Gold",
    "wearer": "Men",
    "occasion": "Gifting",
    "image": "https://images.unsplash.com/photo-1569397288884-4d43d6738fbd?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 38
  },
  {
    "id": "SG0039",
    "name": "Rajwadi Bridal Choker",
    "type": "Necklaces",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1722410180687-b05b50922362?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 39
  },
  {
    "id": "SG0040",
    "name": "Feather Light Daily Chain",
    "type": "Chains",
    "metal": "18K Gold",
    "wearer": "Women",
    "occasion": "Daily Wear",
    "image": "https://images.unsplash.com/photo-1611107683227-e9060eccd846?auto=format&fit=crop&w=700&q=80",
    "isNew": true,
    "bestseller": true,
    "order": 40
  },
  {
    "id": "SG0041",
    "name": "Antique Kada Pair in 22K",
    "type": "Bangles",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1679156271456-d6068c543ee7?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 41
  },
  {
    "id": "SG0042",
    "name": "Velvet Box Bridal Kada Set",
    "type": "Bangles",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1728381031272-ba3f537feadd?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 42
  },
  {
    "id": "SG0043",
    "name": "Heirloom Kada in a Wooden Box",
    "type": "Bangles",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1690175867343-2af70ea57537?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 43
  },
  {
    "id": "SG0044",
    "name": "Diamond Studded Bracelet",
    "type": "Bangles",
    "metal": "Diamond",
    "wearer": "Women",
    "occasion": "Festive",
    "image": "https://images.unsplash.com/photo-1611598935678-c88dca238fce?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 44
  },
  {
    "id": "SG0045",
    "name": "Ornate Bangle Stack, Set of Six",
    "type": "Bangles",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1758995116383-f51775896add?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 45
  },
  {
    "id": "SG0046",
    "name": "Slim Wrist Kada",
    "type": "Bangles",
    "metal": "18K Gold",
    "wearer": "Women",
    "occasion": "Daily Wear",
    "image": "https://images.unsplash.com/photo-1741071520904-37ef3c0fea09?auto=format&fit=crop&w=700&q=80",
    "isNew": true,
    "bestseller": false,
    "order": 46
  },
  {
    "id": "SG0047",
    "name": "Everyday Gold Bracelet",
    "type": "Bangles",
    "metal": "18K Gold",
    "wearer": "Women",
    "occasion": "Daily Wear",
    "image": "https://images.unsplash.com/photo-1740567389909-b36e9cadbef9?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 47
  },
  {
    "id": "SG0048",
    "name": "The Full Bangle Counter Set",
    "type": "Bangles",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1768359666502-306694fa6fcf?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 48
  },
  {
    "id": "SG0049",
    "name": "Twin Kada on Silk",
    "type": "Bangles",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Festive",
    "image": "https://images.unsplash.com/photo-1679156272446-30738eb5c4e7?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 49
  },
  {
    "id": "SG0050",
    "name": "Coral Bead Bangle",
    "type": "Bangles",
    "metal": "Gemstone",
    "wearer": "Women",
    "occasion": "Festive",
    "image": "https://images.unsplash.com/photo-1617191880362-aac615de3c26?auto=format&fit=crop&w=700&q=80",
    "isNew": true,
    "bestseller": false,
    "order": 50
  },
  {
    "id": "SG0051",
    "name": "Pearl Line Bangle",
    "type": "Bangles",
    "metal": "Gemstone",
    "wearer": "Women",
    "occasion": "Office Wear",
    "image": "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 51
  },
  {
    "id": "SG0052",
    "name": "Kids Gold Bangle Pair",
    "type": "Bangles",
    "metal": "18K Gold",
    "wearer": "Kids",
    "occasion": "Gifting",
    "image": "https://images.unsplash.com/photo-1626784214765-754de4c5a77b?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 52
  },
  {
    "id": "SG0053",
    "name": "Rose Gold Pink Stone Ring",
    "type": "Rings",
    "metal": "Rose Gold",
    "wearer": "Women",
    "occasion": "Festive",
    "image": "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 53
  },
  {
    "id": "SG0054",
    "name": "Proposal Solitaire in a Box",
    "type": "Rings",
    "metal": "Diamond",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 54
  },
  {
    "id": "SG0055",
    "name": "Plain Band in 22K Gold",
    "type": "Rings",
    "metal": "22K Gold",
    "wearer": "Men",
    "occasion": "Daily Wear",
    "image": "https://images.unsplash.com/photo-1598560917807-1bae44bd2be8?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 55
  },
  {
    "id": "SG0056",
    "name": "His and Hers Wedding Band Pair",
    "type": "Rings",
    "metal": "18K Gold",
    "wearer": "Men",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1719924998065-0c60e329ef58?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 56
  },
  {
    "id": "SG0057",
    "name": "Pave Diamond Cocktail Ring",
    "type": "Rings",
    "metal": "Diamond",
    "wearer": "Women",
    "occasion": "Festive",
    "image": "https://images.unsplash.com/photo-1607703829739-c05b7beddf60?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 57
  },
  {
    "id": "SG0058",
    "name": "Rose Petal Engagement Ring",
    "type": "Rings",
    "metal": "Diamond",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1518370265276-f22b706aeac8?auto=format&fit=crop&w=700&q=80",
    "isNew": true,
    "bestseller": false,
    "order": 58
  },
  {
    "id": "SG0059",
    "name": "Stacking Ring Trio",
    "type": "Rings",
    "metal": "18K Gold",
    "wearer": "Women",
    "occasion": "Office Wear",
    "image": "https://images.unsplash.com/photo-1481980235850-66e47651e431?auto=format&fit=crop&w=700&q=80",
    "isNew": true,
    "bestseller": false,
    "order": 59
  },
  {
    "id": "SG0060",
    "name": "Ruby Red Statement Ring",
    "type": "Rings",
    "metal": "Gemstone",
    "wearer": "Women",
    "occasion": "Festive",
    "image": "https://images.unsplash.com/photo-1613945407943-59cd755fd69e?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 60
  },
  {
    "id": "SG0061",
    "name": "Classic Six Prong Solitaire",
    "type": "Rings",
    "metal": "Diamond",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1589674668791-4889d2bba4c6?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 61
  },
  {
    "id": "SG0062",
    "name": "Halo Set Diamond Ring",
    "type": "Rings",
    "metal": "Diamond",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1589674781759-c21c37956a44?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 62
  },
  {
    "id": "SG0063",
    "name": "Engagement Ring, Cased",
    "type": "Rings",
    "metal": "Diamond",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1677045419454-e8b201856472?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 63
  },
  {
    "id": "SG0064",
    "name": "Simple Gold Band for Men",
    "type": "Rings",
    "metal": "22K Gold",
    "wearer": "Men",
    "occasion": "Daily Wear",
    "image": "https://images.unsplash.com/photo-1655707063513-a08dad26440e?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 64
  },
  {
    "id": "SG0065",
    "name": "Kids Adjustable Gold Ring",
    "type": "Rings",
    "metal": "18K Gold",
    "wearer": "Kids",
    "occasion": "Gifting",
    "image": "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 65
  },
  {
    "id": "SG0066",
    "name": "Red and White Stone Jhumkas",
    "type": "Earrings",
    "metal": "Gemstone",
    "wearer": "Women",
    "occasion": "Festive",
    "image": "https://images.unsplash.com/photo-1671642883395-0ab89c3ac890?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 66
  },
  {
    "id": "SG0067",
    "name": "Bridal Chandbali Earrings",
    "type": "Earrings",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1653227907864-560dce4c252d?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 67
  },
  {
    "id": "SG0068",
    "name": "Everyday Gold Hoops",
    "type": "Earrings",
    "metal": "18K Gold",
    "wearer": "Women",
    "occasion": "Daily Wear",
    "image": "https://images.unsplash.com/photo-1671644730555-916aa8d8157f?auto=format&fit=crop&w=700&q=80",
    "isNew": true,
    "bestseller": false,
    "order": 68
  },
  {
    "id": "SG0069",
    "name": "Pearl Drop Danglers",
    "type": "Earrings",
    "metal": "Gemstone",
    "wearer": "Women",
    "occasion": "Office Wear",
    "image": "https://images.unsplash.com/photo-1701777892740-88419a701472?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 69
  },
  {
    "id": "SG0070",
    "name": "Solitaire Diamond Tops",
    "type": "Earrings",
    "metal": "Diamond",
    "wearer": "Women",
    "occasion": "Daily Wear",
    "image": "https://images.unsplash.com/photo-1727990865600-91f8cb8b0168?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 70
  },
  {
    "id": "SG0071",
    "name": "Amethyst Vine Ear Cuffs",
    "type": "Earrings",
    "metal": "Gemstone",
    "wearer": "Women",
    "occasion": "Festive",
    "image": "https://images.unsplash.com/photo-1601121141418-c1caa10a2a0b?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 71
  },
  {
    "id": "SG0072",
    "name": "Kids First Gold Studs",
    "type": "Earrings",
    "metal": "18K Gold",
    "wearer": "Kids",
    "occasion": "Gifting",
    "image": "https://images.unsplash.com/photo-1588891805983-fee12d508e31?auto=format&fit=crop&w=700&q=80",
    "isNew": true,
    "bestseller": false,
    "order": 72
  },
  {
    "id": "SG0073",
    "name": "Temple Motif Long Jhumkas",
    "type": "Earrings",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1695049918857-1e27d67782e5?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 73
  },
  {
    "id": "SG0074",
    "name": "Rani Haar in 22K Gold",
    "type": "Necklaces",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1705326452390-3ecf6070595f?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 74
  },
  {
    "id": "SG0075",
    "name": "Pearl and Ruby Choker",
    "type": "Necklaces",
    "metal": "Gemstone",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1721103418312-b0057a8c31c2?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 75
  },
  {
    "id": "SG0076",
    "name": "Emerald Bead Long Haar",
    "type": "Necklaces",
    "metal": "Gemstone",
    "wearer": "Women",
    "occasion": "Festive",
    "image": "https://images.unsplash.com/photo-1722410180670-b6d5a2e704fa?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 76
  },
  {
    "id": "SG0077",
    "name": "Bridal Kundan Collar",
    "type": "Necklaces",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1722410180687-b05b50922362?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 77
  },
  {
    "id": "SG0078",
    "name": "Layered Coin Necklace",
    "type": "Necklaces",
    "metal": "18K Gold",
    "wearer": "Women",
    "occasion": "Office Wear",
    "image": "https://images.unsplash.com/photo-1601121141461-920cb1993441?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 78
  },
  {
    "id": "SG0079",
    "name": "Crowned Pendant Necklace",
    "type": "Necklaces",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Festive",
    "image": "https://images.unsplash.com/photo-1685970731194-e27b477e87ba?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 79
  },
  {
    "id": "SG0080",
    "name": "Amethyst Bead Rope",
    "type": "Necklaces",
    "metal": "Gemstone",
    "wearer": "Women",
    "occasion": "Festive",
    "image": "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?auto=format&fit=crop&w=700&q=80",
    "isNew": true,
    "bestseller": false,
    "order": 80
  },
  {
    "id": "SG0081",
    "name": "Heart Solitaire Pendant",
    "type": "Pendants",
    "metal": "Diamond",
    "wearer": "Women",
    "occasion": "Gifting",
    "image": "https://images.unsplash.com/photo-1605100804567-1ffe942b5cd6?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 81
  },
  {
    "id": "SG0082",
    "name": "Om Pendant in 22K",
    "type": "Pendants",
    "metal": "22K Gold",
    "wearer": "Men",
    "occasion": "Daily Wear",
    "image": "https://images.unsplash.com/photo-1569397288884-4d43d6738fbd?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 82
  },
  {
    "id": "SG0083",
    "name": "Baby Name Pendant",
    "type": "Pendants",
    "metal": "18K Gold",
    "wearer": "Kids",
    "occasion": "Gifting",
    "image": "https://images.unsplash.com/photo-1722410180644-ff76ef805092?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 83
  },
  {
    "id": "SG0084",
    "name": "Charm Locket on a Chain",
    "type": "Pendants",
    "metal": "18K Gold",
    "wearer": "Women",
    "occasion": "Gifting",
    "image": "https://images.unsplash.com/photo-1623321673989-830eff0fd59f?auto=format&fit=crop&w=700&q=80",
    "isNew": true,
    "bestseller": false,
    "order": 84
  },
  {
    "id": "SG0085",
    "name": "Heavy Rope Chain for Men",
    "type": "Chains",
    "metal": "22K Gold",
    "wearer": "Men",
    "occasion": "Festive",
    "image": "https://images.unsplash.com/photo-1611107683227-e9060eccd846?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 85
  },
  {
    "id": "SG0086",
    "name": "Box Chain, 20 inch",
    "type": "Chains",
    "metal": "18K Gold",
    "wearer": "Men",
    "occasion": "Daily Wear",
    "image": "https://images.unsplash.com/photo-1601121141499-17ae80afc03a?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 86
  },
  {
    "id": "SG0087",
    "name": "Gemstone Line Chain",
    "type": "Chains",
    "metal": "Gemstone",
    "wearer": "Women",
    "occasion": "Office Wear",
    "image": "https://images.unsplash.com/photo-1589095053205-8fc842336f4a?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 87
  },
  {
    "id": "SG0088",
    "name": "Kids Light Chain",
    "type": "Chains",
    "metal": "18K Gold",
    "wearer": "Kids",
    "occasion": "Gifting",
    "image": "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 88
  },
  {
    "id": "SG0089",
    "name": "Diamond Vati Mangalsutra",
    "type": "Mangalsutra",
    "metal": "Diamond",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1600862754152-80a263dd564f?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 89
  },
  {
    "id": "SG0090",
    "name": "Short Daily Mangalsutra",
    "type": "Mangalsutra",
    "metal": "18K Gold",
    "wearer": "Women",
    "occasion": "Daily Wear",
    "image": "https://images.unsplash.com/photo-1620656798579-1984d9e87df7?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 90
  },
  {
    "id": "SG0091",
    "name": "Traditional Long Mangalsutra",
    "type": "Mangalsutra",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1589095053205-8fc842336f4a?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 91
  },
  {
    "id": "SG0092",
    "name": "Maharashtrian Nath",
    "type": "Nose Pins",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1603974372039-adc49044b6bd?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 92
  },
  {
    "id": "SG0093",
    "name": "Tiny Diamond Nose Stud",
    "type": "Nose Pins",
    "metal": "Diamond",
    "wearer": "Women",
    "occasion": "Daily Wear",
    "image": "https://images.unsplash.com/photo-1578503803703-e818b8a0e00b?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 93
  },
  {
    "id": "SG0094",
    "name": "Complete Bridal Trunk Set",
    "type": "Bridal Sets",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1705326454924-f6777522b030?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": true,
    "order": 94
  },
  {
    "id": "SG0095",
    "name": "Polki Reception Set",
    "type": "Bridal Sets",
    "metal": "Gemstone",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1651160670627-2896ddf7822f?auto=format&fit=crop&w=700&q=80",
    "isNew": false,
    "bestseller": false,
    "order": 95
  },
  {
    "id": "SG0096",
    "name": "Haldi Ceremony Light Set",
    "type": "Bridal Sets",
    "metal": "22K Gold",
    "wearer": "Women",
    "occasion": "Wedding",
    "image": "https://images.unsplash.com/photo-1617191880362-aac615de3c26?auto=format&fit=crop&w=700&q=80",
    "isNew": true,
    "bestseller": false,
    "order": 96
  }
];
